name: Welcome to @chakra-ui/vue 

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.CHAKRA_VUE_TOKEN }}
        issue-message: 'Hi! Thanks for opening an issue with @chakra-ui/vue!'
        pr-message: 'Ahoy! Thanks for contributing to @chakra-ui/vue!'
