# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build & Test Components

on:
  push:
    branches:
      - master
    paths:
      - "packages/**"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 12.x
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
      with:
        # This makes Actions fetch all Git history
        # so that Changesets can generate changelogs with the correct commits
        fetch-depth: 0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn

    - name: Bootstrap
      run: yarn bootstrap

    - name: Linting
      run: yarn lint

    - name: Testing components
      run: yarn test
      env:
        CI: true

    - name: Building packages
      run: yarn build --if-present

    - name: Setup CI Git User
      run: |
        git config --global user.email "jbakebwa@gmail.com"
        git config --global user.name "codebender828"
    
    - name: Publish packages
      uses: changesets/action@master
      with:
        publish: yarn release
        commit: "chore(release): version packages"
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}    
